
name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm test
    - run: npm run build
    - name: "version bump"
      uses: "phips28/gh-action-bump-version@master"
      with:
        tag-prefix: 'v'
    - run: npm publish
